"""Settings for the ESI Auth application."""

from pathlib import Path
from typing import Any, TypedDict

import typer
from pydantic import Field
from pydantic_settings import BaseSettings, SettingsConfigDict
from whenever import Instant

from esi_auth import __app_name__, __url__, __version__

_app_env_prefix = "PFMSOFT_ESI_AUTH_"
USER_AGENT = f"{__app_name__}/{__version__} (+{__url__})"
NAMESPACE = "pfmsoft"
APPLICATION_NAME = "esi-auth"
DEFAULT_APP_DIR = Path(typer.get_app_dir(f"{NAMESPACE}-{APPLICATION_NAME}"))


class ConfigDict(TypedDict):
    """Configuration dictionary type for EsiAuthSettings.

    This TypedDict defines the possible keys and their types that can be
    used to configure the EsiAuthSettings via the get_settings function.
    """

    log_dir: Path
    app_dir: Path
    connection_string: str
    auth_server_timeout: int


class EsiAuthSettings(BaseSettings):
    """Settings for the ESI Auth application."""

    log_dir: Path = Field(
        default=DEFAULT_APP_DIR / "logs", description="Directory for log files."
    )
    app_dir: Path = Field(
        default=DEFAULT_APP_DIR, description="Directory for application data."
    )
    connection_string: str = Field(
        default=f"esi-auth-file:{DEFAULT_APP_DIR.resolve()}/esi-auth-store.json",
        description="Connection string for a json based auth store.",
    )
    auth_server_timeout: int = Field(
        default=300,
        description="Timeout in seconds for the auth server to respond.",
        ge=1,
        le=300,  # Max 5 minutes
    )

    model_config = SettingsConfigDict(
        env_prefix=_app_env_prefix,
        env_file=(f"{DEFAULT_APP_DIR.resolve()}/.esi-auth.env", ".esi-auth.env"),
        env_file_encoding="utf-8",
    )


def get_settings(
    config_dict: ConfigDict | None = None, **kwargs: Any
) -> EsiAuthSettings:
    """Retrieve the ESI Auth settings.

    An optional config_dict can be provided to supply configuration values.
    These values will override any defaults in EsiAuthSettings, as well as values
    loaded from env files or the os environment. This is useful for testing, debugging,
    or programmatically setting configuration for third party integrations.

    Args:
        config_dict: Optional dictionary containing app configuration values.
            If provided, values from this dict will be combined with
            kwargs, with kwargs taking precedence for duplicate keys.
        **kwargs: Additional keyword arguments to pass directly to EsiAuthSettings.
            These will override any matching keys from config_dict if both are provided.
            They are intended to allow for dynamic overrides of pydantic BaseSettings behavior.

    Returns:
        An instance of EsiAuthSettings with the loaded configuration.

    Examples:
        >>> settings = get_settings()
        >>> settings = get_settings(config_dict=ConfigDict(key="value"))
        >>> settings = get_settings(
        ...     config_dict=ConfigDict(key="value"), pydantic_base_setting="another_value"
        ... )
    """
    if config_dict is not None:
        combined_kwargs: dict[str, Any] = config_dict | kwargs
        return EsiAuthSettings(**combined_kwargs)
    else:
        return EsiAuthSettings(**kwargs)


def env_example(app_dir: Path | None = None) -> str:
    """Provide an example of the .esi-auth.env file configuration for user-agent settings.

    Supply the application directory if it is not the default. if the app_dir is supplied,
    the APP_DIR and LOG_DIR, and CONNECTION_STRING lines will be uncommented.

    Args:
        app_dir: Optional Path to the application directory. If None, default is used.

    Returns:
        A string containing the example .esi-auth.env configuration.
    """
    env_example_str = f"""# ESI Auth .esi-auth.env Configuration Example

# Generated by {__app_name__} v{__version__} at {Instant.now().format_iso()}

# Instructions:
# Uncomment lines to use them.
# Replace the default values with your actual information as needed.

# esi-auth will look for this file in the application data directory and in the
# current working directory. If found in both places, settings from the current working
# directory take precedence.

# The App Directory is where application data is stored.
{"" if app_dir else "#"}{_app_env_prefix}APP_DIR="{app_dir.resolve() if app_dir else DEFAULT_APP_DIR.resolve()}"

##### Logging and Store Configuration #####

# The logging directory is where log files will be stored.
{"" if app_dir else "#"}{_app_env_prefix}LOG_DIR="${{{_app_env_prefix}APP_DIR}}/logs"



# Connection string for the auth store. This example uses a file-based store.
# possible formats: 
#  - "esi-auth-file:/path/to/store.json"
#  - "esi-auth-sqlite:/path/to/store.db" (for future use)
{"" if app_dir else "#"}{_app_env_prefix}CONNECTION_STRING="esi-auth-file:${{{_app_env_prefix}APP_DIR}}/esi-auth-store.json"

##### Auth Server Timeout #####

# Timeout in seconds for the auth server to respond. Default is 300 seconds (5 minutes).
#{_app_env_prefix}AUTH_SERVER_TIMEOUT="300"


"""
    return env_example_str
